  # <b> <p align="center"> <span style="color: 	tomato "> FUNDAMENTALS EXERCISES  </span> </p> </b>

In [1]:
import torch
import numpy as np
import pandas as pd

## Create a random tensor with shape (7, 7).

In [2]:
random_tensor=torch.rand(size=(7,7))
random_tensor


tensor([[0.9580, 0.5341, 0.9014, 0.1371, 0.8208, 0.9436, 0.2097],
        [0.3013, 0.7574, 0.7820, 0.7774, 0.0197, 0.9258, 0.3218],
        [0.7058, 0.7150, 0.2850, 0.5839, 0.5606, 0.6249, 0.0473],
        [0.4560, 0.8092, 0.3985, 0.3490, 0.3007, 0.0524, 0.4397],
        [0.4840, 0.1283, 0.8984, 0.4699, 0.5765, 0.1339, 0.3277],
        [0.2544, 0.7580, 0.9135, 0.6748, 0.3865, 0.1105, 0.1803],
        [0.8145, 0.8898, 0.9481, 0.6958, 0.7868, 0.5667, 0.5210]])

## Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [3]:
random_tensor_A=torch.rand(size=(1,7))
torch.matmul(random_tensor, random_tensor_A.T)

tensor([[2.4243],
        [1.9453],
        [1.8698],
        [1.4970],
        [1.1110],
        [1.2969],
        [2.5532]])

## Set the random seed to 0 and do exercises 2 & 3 over again.

In [4]:
RANDOM_SEED=0
torch.manual_seed(RANDOM_SEED)

random_tensor_with_seed_A=torch.rand(size=(7,7))
torch.manual_seed(RANDOM_SEED)
random_tensor_with_seed_B=torch.rand(size=(1,7))
torch.matmul(random_tensor_with_seed_A,random_tensor_with_seed_B.T)


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

## Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [5]:
torch.cuda.manual_seed=1234

### Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [6]:
#set random seed
torch.manual_seed(1234)

#check for access to GPU

device='cuda' if torch.cuda.is_available() else "cpu"

print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

## Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [7]:

# Perform matmul on tensor_A and tensor_B
# tensor_C = torch.matmul(tensor_A, tensor_B) # won't work because of shape error
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

## Find the maximum and minimum values of the output of 7.

In [8]:

# Find max
max = torch.max(tensor_C)

# Find min
min = torch.min(tensor_C)
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

## Find the maximum and minimum index values of the output of 7.

In [9]:


# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

##  Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [10]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
