  # <b> <p align="center"> <span style="color: 	tomato "> FUNDAMENTALS EXERCISES  </span> </p> </b>

In [1]:
import torch
import numpy as np
import pandas as pd

## Create a random tensor with shape (7, 7).

In [2]:
random_tensor=torch.rand(size=(7,7))
random_tensor


tensor([[0.8793, 0.0532, 0.7452, 0.6484, 0.9478, 0.0681, 0.1526],
        [0.8349, 0.6992, 0.3243, 0.2094, 0.5714, 0.8602, 0.9639],
        [0.3783, 0.7291, 0.4076, 0.0884, 0.3918, 0.1273, 0.5873],
        [0.2885, 0.6587, 0.5448, 0.9313, 0.5378, 0.7830, 0.7268],
        [0.5136, 0.7603, 0.5351, 0.1010, 0.5538, 0.4244, 0.9878],
        [0.4529, 0.4767, 0.1261, 0.0710, 0.6267, 0.9081, 0.2857],
        [0.4547, 0.1360, 0.7070, 0.2437, 0.3493, 0.8222, 0.6336]])

## Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [3]:
random_tensor_A=torch.rand(size=(1,7))
torch.matmul(random_tensor, random_tensor_A.T)

tensor([[1.5073],
        [2.7804],
        [1.7420],
        [2.8832],
        [2.5029],
        [1.7762],
        [2.1863]])

## Set the random seed to 0 and do exercises 2 & 3 over again.

In [4]:
RANDOM_SEED=0
torch.manual_seed(RANDOM_SEED)

random_tensor_with_seed_A=torch.rand(size=(7,7))
torch.manual_seed(RANDOM_SEED)
random_tensor_with_seed_B=torch.rand(size=(1,7))
torch.matmul(random_tensor_with_seed_A,random_tensor_with_seed_B.T)


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

## Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [5]:
torch.cuda.manual_seed=1234

### Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [6]:
#set random seed
torch.manual_seed(1234)

#check for access to GPU

device='cuda' if torch.cuda.is_available() else "cpu"

print(f"Device: {device}")

# Create two random tensors on GPU
tensor_A = torch.rand(size=(2,3)).to(device)
tensor_B = torch.rand(size=(2,3)).to(device)
tensor_A, tensor_B

Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

## Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [7]:

# Perform matmul on tensor_A and tensor_B
# tensor_C = torch.matmul(tensor_A, tensor_B) # won't work because of shape error
tensor_C = torch.matmul(tensor_A, tensor_B.T)
tensor_C, tensor_C.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

## Find the maximum and minimum values of the output of 7.

In [8]:

# Find max
max = torch.max(tensor_C)

# Find min
min = torch.min(tensor_C)
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

## Find the maximum and minimum index values of the output of 7.

In [9]:


# Find arg max
arg_max = torch.argmax(tensor_C)

# Find arg min
arg_min = torch.argmin(tensor_C)
arg_max, arg_min

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

##  Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [10]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
